name: diracx
channels:
  - diracgrid
  - conda-forge
  - nodefaults
dependencies:
  - authlib
  - aiomysql
  - aiosqlite
  - email-validator
  - fastapi
  - isodate
  - opensearch-py
  - pyjwt
  - coverage
  - python-dotenv
  - python-jose
  - python-multipart
  - sqlalchemy
  - uvicorn
  - aiobotocore >=2.12
  - botocore
  - ca-policy-lcg
  - opentelemetry-api
  - opentelemetry-exporter-otlp
  - opentelemetry-instrumentation-fastapi
  - opentelemetry-instrumentation-logging
  - opentelemetry-sdk