name: diracx
channels:
  - diracgrid
  - conda-forge
  - nodefaults
dependencies:
  - authlib
  - aiohttp
  - aiomysql
  - aiosqlite
  - azure-core
  - cachetools
  ########
  # Building the docker image on some system may fail
  # as long as this bug is still present
  # https://github.com/DaanDeMeyer/reproc/pull/103
  # or that this is merged
  # https://github.com/conda-forge/reproc-feedstock/pull/10
  # If it does, we need to comment out `dirac-grid` here
  # and install it via pip
  - dirac-grid
  - m2crypto >=0.38.0
  - python-gfal2
  - importlib_resources
  #######
  - email-validator
  - fastapi
  - git
  - gitpython
  - httpx
  - isodate
  - opensearch-py
  - pydantic >=2
  - pydantic-settings
  - pyjwt
  - python
  - coverage
  - python-dotenv
  - python-jose
  - python-multipart
  - pyyaml
  - requests
  - rich
  - sqlalchemy
  # Exclude version 0.12.4 of typer: https://github.com/DIRACGrid/diracx/issues/280
  - typer!=0.12.4
  - uvicorn
  - aiobotocore >=2.12
  - botocore
  - git
  - pip
