name: diracx
channels:
  - diracgrid
  - conda-forge
  - nodefaults
dependencies:
  - aiohttp
  - azure-core
  - cachetools
  - isodate
  - python-dotenv
  - python-multipart
  - rich
  # Exclude version >= 0.12.4 of typer: https://github.com/DIRACGrid/diracx/issues/280
  - typer<0.12.4
